name: CD Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.GHCR_IMAGE }}
            docker stop devops-app || true
            docker rm devops-app || true
            docker run -d --name devops-app -p 8080:8080 ${{ secrets.GHCR_IMAGE }}
