name: CD Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Deploy to DEV
        run: |
          echo "Deploying image ghcr.io/jmgiraldoz17/proyecto-devops:dev to DEV"
